name: Test

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Dummy Coverage Directory
        run: |
          mkdir -p ./coverage
          echo "dummy coverage data" > ./coverage/index.html

      - name: Upload rspec-coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rspec-coverage
          path: ./coverage
